export const USE_API = false;
export const API_URL = "/api/events";

const D = "2026-09-13";
const Z = "-04:00";
const at = (t) => `${D}T${t}:00${Z}`;

export const SEED_EVENTS = [
  {
    id: "evt_001",
    title: "Board game night, they pair you up",
    venue: "Snakes & Lattes Annex",
    startsAt: at("19:00"), endsAt: at("22:00"),
    travelMinutes: 14, travelMode: "transit",
    price: 0, currency: "CAD",
    tags: ["games", "social"],
    circumstances: ["solo-friendly", "free", "step-free", "beginner-welcome"],
    goingCount: 7, matchScore: 0.82,
    source: { name: "Instagram", url: "https://instagram.com/snakesandlattes" },
    imageUrl: null,
    description: "Drop-in from seven. Tell the host you came alone and they will sit you at a table that is short a player."
  },
  {
    id: "evt_002",
    title: "Kensington market run club, easy 5k",
    venue: "Bellevue Square Park",
    startsAt: at("18:45"), endsAt: at("20:00"),
    travelMinutes: 9, travelMode: "walk",
    price: 0, currency: "CAD",
    tags: ["outdoors", "fitness"],
    circumstances: ["solo-friendly", "free", "beginner-welcome"],
    goingCount: 22, matchScore: 0.79,
    source: { name: "Instagram", url: "https://instagram.com/kensingtonrunclub" },
    imageUrl: null,
    description: "Two pace groups, the back one walks the hills. Bag drop at the gazebo."
  },
  {
    id: "evt_003",
    title: "Open mic upstairs, sign up at eight",
    venue: "The Cameron House",
    startsAt: at("20:30"), endsAt: at("23:00"),
    travelMinutes: 6, travelMode: "walk",
    price: 0, currency: "CAD",
    tags: ["music"],
    circumstances: ["solo-friendly", "free"],
    goingCount: 31, matchScore: 0.74,
    source: { name: "Eventbrite", url: "https://eventbrite.ca/e/cameron-open-mic" },
    imageUrl: null,
    description: "Back room, pass the hat. You can just watch, nobody will make you play."
  },
  {
    id: "evt_004",
    title: "Life drawing, no experience needed",
    venue: "Artscape Youngplace",
    startsAt: at("19:00"), endsAt: at("21:30"),
    travelMinutes: 12, travelMode: "transit",
    price: 15, currency: "CAD",
    tags: ["art"],
    circumstances: ["beginner-welcome", "quiet", "step-free", "no-alcohol"],
    goingCount: 12, matchScore: 0.71,
    source: { name: "Eventbrite", url: "https://eventbrite.ca/e/youngplace-life-drawing" },
    imageUrl: null,
    description: "Paper and charcoal provided. Short poses first, one long pose after the break."
  },
  {
    id: "evt_005",
    title: "Pickup volleyball, nets already up",
    venue: "Trinity Bellwoods Park",
    startsAt: at("17:30"), endsAt: at("19:30"),
    travelMinutes: 11, travelMode: "bike",
    price: 0, currency: "CAD",
    tags: ["outdoors", "fitness", "social"],
    circumstances: ["solo-friendly", "free", "beginner-welcome"],
    goingCount: 18, matchScore: 0.64,
    source: { name: "Meetup", url: "https://meetup.com/toronto-pickup-volleyball" },
    imageUrl: null,
    description: "Two courts on the south side. Rotate in, losers sit."
  },
  {
    id: "evt_006",
    title: "Early jazz set, trio",
    venue: "The Rex Hotel",
    startsAt: at("18:45"), endsAt: at("21:00"),
    travelMinutes: 7, travelMode: "walk",
    price: 10, currency: "CAD",
    tags: ["music"],
    circumstances: ["solo-friendly", "step-free"],
    goingCount: 26, matchScore: 0.68,
    source: { name: "Venue site", url: "https://therex.ca/calendar" },
    imageUrl: null,
    description: "Cover at the door, cash or tap. Seats at the bar if you get there before the set."
  },
  {
    id: "evt_007",
    title: "Silent book club, bring whatever you're reading",
    venue: "Glad Day Bookshop",
    startsAt: at("19:00"), endsAt: at("20:30"),
    travelMinutes: 18, travelMode: "transit",
    price: 0, currency: "CAD",
    tags: ["books", "social"],
    circumstances: ["solo-friendly", "free", "quiet", "step-free", "no-alcohol"],
    goingCount: 9, matchScore: 0.77,
    source: { name: "Instagram", url: "https://instagram.com/gladdaybookshop" },
    imageUrl: null,
    description: "An hour of reading in the same room, then anyone who wants to talk about it stays."
  },
  {
    id: "evt_008",
    title: "Chess tables, all levels",
    venue: "Christie Pits Park",
    startsAt: at("17:00"), endsAt: at("19:00"),
    travelMinutes: 16, travelMode: "transit",
    price: 0, currency: "CAD",
    tags: ["games"],
    circumstances: ["solo-friendly", "free", "no-alcohol"],
    goingCount: 6, matchScore: 0.58,
    source: { name: "Meetup", url: "https://meetup.com/christie-pits-chess" },
    imageUrl: null,
    description: "Boards on the concrete tables by the bandshell. Someone always has a spare clock."
  },
  {
    id: "evt_009",
    title: "Intro bouldering, shoes included",
    venue: "Basecamp Climbing Bathurst",
    startsAt: at("21:30"), endsAt: at("23:00"),
    travelMinutes: 26, travelMode: "transit",
    price: 25, currency: "CAD",
    tags: ["fitness", "outdoors"],
    circumstances: ["beginner-welcome", "solo-friendly", "no-alcohol"],
    goingCount: 14, matchScore: 0.66,
    source: { name: "Venue site", url: "https://basecampclimbing.ca/intro" },
    imageUrl: null,
    description: "Forty minutes of teaching, then the walls are yours until close."
  },
  {
    id: "evt_010",
    title: "Trivia, teams of four or fewer",
    venue: "Sneaky Dee's",
    startsAt: at("20:00"), endsAt: at("22:30"),
    travelMinutes: 8, travelMode: "walk",
    price: 0, currency: "CAD",
    tags: ["games", "social"],
    circumstances: ["solo-friendly", "free"],
    goingCount: 41, matchScore: 0.7,
    source: { name: "Instagram", url: "https://instagram.com/sneakydees" },
    imageUrl: null,
    description: "Show up alone and the host will stick you on a short team. Kitchen runs late."
  },
  {
    id: "evt_011",
    title: "Swing dance drop-in, lesson first",
    venue: "Dovercourt House",
    startsAt: at("19:30"), endsAt: at("23:00"),
    travelMinutes: 21, travelMode: "transit",
    price: 12, currency: "CAD",
    tags: ["music", "social", "fitness"],
    circumstances: ["solo-friendly", "beginner-welcome", "no-alcohol"],
    goingCount: 55, matchScore: 0.73,
    source: { name: "Venue site", url: "https://dovercourthouse.ca/swing" },
    imageUrl: null,
    description: "Beginner lesson at half seven, no partner needed, the floor opens at half eight."
  },
  {
    id: "evt_012",
    title: "Night photo walk along the ravine",
    venue: "Evergreen Brick Works",
    startsAt: at("18:30"), endsAt: at("20:30"),
    travelMinutes: 34, travelMode: "transit",
    price: 0, currency: "CAD",
    tags: ["outdoors", "art"],
    circumstances: ["solo-friendly", "free", "quiet", "beginner-welcome"],
    goingCount: 11, matchScore: 0.62,
    source: { name: "Meetup", url: "https://meetup.com/toronto-night-photo" },
    imageUrl: null,
    description: "Phone cameras are fine. Meet by the welcome centre, we loop the quarry and come back."
  },
  {
    id: "evt_013",
    title: "Ping pong social, singles ladder",
    venue: "SPIN Toronto",
    startsAt: at("21:15"), endsAt: at("23:00"),
    travelMinutes: 13, travelMode: "walk",
    price: 5, currency: "CAD",
    tags: ["games", "social", "fitness"],
    circumstances: ["solo-friendly", "beginner-welcome", "step-free"],
    goingCount: 19, matchScore: 0.69,
    source: { name: "Instagram", url: "https://instagram.com/spintoronto" },
    imageUrl: null,
    description: "Five dollars gets you on the ladder. Paddles at the front desk."
  },
  {
    id: "evt_014",
    title: "Beginner salsa, no partner needed",
    venue: "Lula Lounge",
    startsAt: at("19:30"), endsAt: at("22:00"),
    travelMinutes: 29, travelMode: "transit",
    price: 18, currency: "CAD",
    tags: ["music", "social"],
    circumstances: ["solo-friendly", "beginner-welcome", "step-free"],
    goingCount: 37, matchScore: 0.61,
    source: { name: "Venue site", url: "https://lula.ca/events" },
    imageUrl: null,
    description: "Class rotates partners the whole hour, so coming alone is normal here."
  },
  {
    id: "evt_015",
    title: "Sunset paddle, boats provided",
    venue: "Cherry Beach Paddle Club",
    startsAt: at("18:50"), endsAt: at("20:30"),
    travelMinutes: 47, travelMode: "transit",
    price: 20, currency: "CAD",
    tags: ["outdoors", "fitness"],
    circumstances: ["beginner-welcome", "no-alcohol"],
    goingCount: 8, matchScore: 0.44,
    source: { name: "Venue site", url: "https://cherrybeachpaddle.ca" },
    imageUrl: null,
    description: "Tandem canoes, they will match you with someone if you turn up alone."
  },
  {
    id: "evt_016",
    title: "Korean home cooking, one dish",
    venue: "Ryu Kitchen Studio, Bloor West",
    startsAt: at("18:00"), endsAt: at("20:00"),
    travelMinutes: 31, travelMode: "transit",
    price: 45, currency: "CAD",
    tags: ["food"],
    circumstances: ["beginner-welcome", "no-alcohol", "step-free"],
    goingCount: 10, matchScore: 0.4,
    source: { name: "Eventbrite", url: "https://eventbrite.ca/e/ryu-kitchen-banchan" },
    imageUrl: null,
    description: "You make banchan and eat what you made. Aprons and containers included."
  },
  {
    id: "evt_017",
    title: "Late show, two local bands",
    venue: "The Horseshoe Tavern",
    startsAt: at("21:30"), endsAt: at("23:00"),
    travelMinutes: 5, travelMode: "walk",
    price: 22, currency: "CAD",
    tags: ["music"],
    circumstances: ["solo-friendly"],
    goingCount: 64, matchScore: 0.53,
    source: { name: "Venue site", url: "https://horseshoetavern.com" },
    imageUrl: null,
    description: "Doors at nine, first band closer to half ten."
  },
  {
    id: "evt_018",
    title: "Dog park meetup, bring or borrow",
    venue: "Stanley Park South",
    startsAt: at("17:15"), endsAt: at("18:30"),
    travelMinutes: 12, travelMode: "walk",
    price: 0, currency: "CAD",
    tags: ["outdoors", "social"],
    circumstances: ["free", "solo-friendly", "kid-friendly", "step-free"],
    goingCount: 15, matchScore: 0.38,
    source: { name: "Facebook", url: "https://facebook.com/groups/stanleyparkdogs" },
    imageUrl: null,
    description: "Regulars gather by the west gate before dark."
  },
  {
    id: "evt_019",
    title: "Repair café, bring the broken thing",
    venue: "Wychwood Barns",
    startsAt: at("17:00"), endsAt: at("20:00"),
    travelMinutes: 24, travelMode: "transit",
    price: 0, currency: "CAD",
    tags: ["making", "social"],
    circumstances: ["free", "step-free", "kid-friendly", "no-alcohol"],
    goingCount: 13, matchScore: 0.47,
    source: { name: "Facebook", url: "https://facebook.com/wychwoodrepaircafe" },
    imageUrl: null,
    description: "Volunteers fix lamps, bikes and small electronics while you wait."
  },
  {
    id: "evt_020",
    title: "Pub quiz for people who hate pub quizzes",
    venue: "The Only Cafe, Danforth",
    startsAt: at("20:00"), endsAt: at("22:00"),
    travelMinutes: 52, travelMode: "transit",
    price: 0, currency: "CAD",
    tags: ["games", "social"],
    circumstances: ["free", "solo-friendly"],
    goingCount: 24, matchScore: 0.55,
    source: { name: "Instagram", url: "https://instagram.com/theonlycafe" },
    imageUrl: null,
    description: "No sports round, no capital cities. Mostly music and bad film."
  },
  {
    id: "evt_021",
    title: "Ultimate frisbee, mixed, drop in",
    venue: "Riverdale Park East",
    startsAt: at("18:15"), endsAt: at("20:00"),
    travelMinutes: 28, travelMode: "bike",
    price: 5, currency: "CAD",
    tags: ["outdoors", "fitness"],
    circumstances: ["beginner-welcome", "solo-friendly"],
    goingCount: 20, matchScore: 0.5,
    source: { name: "Meetup", url: "https://meetup.com/toronto-drop-in-ultimate" },
    imageUrl: null,
    description: "Bring a light and a dark shirt. They stop when the light goes."
  },
  {
    id: "evt_022",
    title: "Screenprinting open studio",
    venue: "Open Studio, Distillery District",
    startsAt: at("19:00"), endsAt: at("22:00"),
    travelMinutes: 49, travelMode: "transit",
    price: 30, currency: "CAD",
    tags: ["art", "making"],
    circumstances: ["beginner-welcome", "step-free", "no-alcohol"],
    goingCount: 7, matchScore: 0.52,
    source: { name: "Venue site", url: "https://openstudio.ca/open-studio-nights" },
    imageUrl: null,
    description: "Pull one shirt or ten. Ink and squeegees are shared, bring your own garment."
  },
  {
    id: "evt_023",
    title: "Astronomy night, telescopes out if clear",
    venue: "High Park, Hillside Gardens",
    startsAt: at("21:20"), endsAt: at("23:00"),
    travelMinutes: 42, travelMode: "transit",
    price: 0, currency: "CAD",
    tags: ["outdoors", "science"],
    circumstances: ["free", "quiet", "kid-friendly", "solo-friendly"],
    goingCount: 17, matchScore: 0.49,
    source: { name: "Facebook", url: "https://facebook.com/groups/rascto" },
    imageUrl: null,
    description: "Members set up four or five scopes. Cancelled without notice if it clouds over."
  },
  {
    id: "evt_024",
    title: "Beginner bachata, first class free",
    venue: "Steps Dance Studio, Ossington",
    startsAt: at("21:15"), endsAt: at("22:30"),
    travelMinutes: 19, travelMode: "transit",
    price: 0, currency: "CAD",
    tags: ["music", "social", "fitness"],
    circumstances: ["free", "beginner-welcome", "solo-friendly", "no-alcohol"],
    goingCount: 28, matchScore: 0.57,
    source: { name: "Instagram", url: "https://instagram.com/stepsdanceto" },
    imageUrl: null,
    description: "Late class, mostly people coming off shift."
  },
  {
    id: "evt_025",
    title: "Storytelling night, five readers",
    venue: "Burdock Music Hall",
    startsAt: at("19:45"), endsAt: at("22:00"),
    travelMinutes: 23, travelMode: "transit",
    price: 14, currency: "CAD",
    tags: ["books", "music"],
    circumstances: ["solo-friendly", "step-free"],
    goingCount: 34, matchScore: 0.6,
    source: { name: "Venue site", url: "https://burdockto.com/music-hall" },
    imageUrl: null,
    description: "True stories, ten minutes each, no notes allowed."
  },
  {
    id: "evt_026",
    title: "Sauna and cold plunge social",
    venue: "Othership Adelaide",
    startsAt: at("21:30"), endsAt: at("23:00"),
    travelMinutes: 10, travelMode: "walk",
    price: 55, currency: "CAD",
    tags: ["fitness", "social"],
    circumstances: ["no-alcohol", "solo-friendly"],
    goingCount: 25, matchScore: 0.35,
    source: { name: "Venue site", url: "https://othership.us/toronto" },
    imageUrl: null,
    description: "Guided session, phones stay in the locker."
  },
  {
    id: "evt_027",
    title: "Community garden work night",
    venue: "Alexandra Park Community Garden",
    startsAt: at("17:45"), endsAt: at("19:15"),
    travelMinutes: 4, travelMode: "walk",
    price: 0, currency: "CAD",
    tags: ["outdoors", "making"],
    circumstances: ["free", "solo-friendly", "kid-friendly", "no-alcohol"],
    goingCount: 9, matchScore: 0.51,
    source: { name: "Facebook", url: "https://facebook.com/groups/alexandraparkgarden" },
    imageUrl: null,
    description: "Weeding and bed turnover. Tools are in the shed, gloves are not, bring your own."
  },
  {
    id: "evt_028",
    title: "Board game swap and play",
    venue: "401 Games, Yonge Street",
    startsAt: at("18:00"), endsAt: at("21:00"),
    travelMinutes: 17, travelMode: "transit",
    price: 0, currency: "CAD",
    tags: ["games"],
    circumstances: ["free", "solo-friendly", "step-free", "beginner-welcome"],
    goingCount: 16, matchScore: 0.63,
    source: { name: "Instagram", url: "https://instagram.com/401games" },
    imageUrl: null,
    description: "Bring a game you are done with, leave with one you are not."
  },
  {
    id: "evt_029",
    title: "Beach volleyball under lights",
    venue: "Ashbridges Bay",
    startsAt: at("19:00"), endsAt: at("21:30"),
    travelMinutes: 50, travelMode: "transit",
    price: 8, currency: "CAD",
    tags: ["outdoors", "fitness"],
    circumstances: ["beginner-welcome", "solo-friendly"],
    goingCount: 21, matchScore: 0.33,
    source: { name: "Meetup", url: "https://meetup.com/ashbridges-beach-volleyball" },
    imageUrl: null,
    description: "Six lit courts, drop-ins fill the gaps at seven."
  },
  {
    id: "evt_030",
    title: "Choir for people who can't sing",
    venue: "Church of the Holy Trinity",
    startsAt: at("19:00"), endsAt: at("20:30"),
    travelMinutes: 15, travelMode: "walk",
    price: 0, currency: "CAD",
    tags: ["music"],
    circumstances: ["free", "beginner-welcome", "solo-friendly", "step-free", "no-alcohol"],
    goingCount: 30, matchScore: 0.72,
    source: { name: "Facebook", url: "https://facebook.com/groups/holytrinitychoir" },
    imageUrl: null,
    description: "No audition, no reading music. They teach by ear in four parts."
  },
  {
    id: "evt_031",
    title: "Skate session, beginners at the shallow end",
    venue: "Vanderhoof Skate Park",
    startsAt: at("17:30"), endsAt: at("19:30"),
    travelMinutes: 44, travelMode: "transit",
    price: 0, currency: "CAD",
    tags: ["outdoors", "fitness"],
    circumstances: ["free", "beginner-welcome", "solo-friendly"],
    goingCount: 12, matchScore: 0.3,
    source: { name: "Instagram", url: "https://instagram.com/vanderhoofskate" },
    imageUrl: null,
    description: "Loaner boards from the shop trailer until they run out."
  },
  {
    id: "evt_032",
    title: "Documentary screening, director in the room",
    venue: "Revue Cinema, Roncesvalles",
    startsAt: at("19:15"), endsAt: at("21:45"),
    travelMinutes: 48, travelMode: "transit",
    price: 16, currency: "CAD",
    tags: ["film"],
    circumstances: ["solo-friendly", "step-free", "quiet"],
    goingCount: 45, matchScore: 0.56,
    source: { name: "Venue site", url: "https://revuecinema.ca" },
    imageUrl: null,
    description: "Ninety minutes, then twenty of questions."
  },
  {
    id: "evt_033",
    title: "Language exchange, six tables",
    venue: "Hot Docs Ted Rogers Cinema cafe",
    startsAt: at("18:00"), endsAt: at("20:00"),
    travelMinutes: 22, travelMode: "transit",
    price: 0, currency: "CAD",
    tags: ["social", "language"],
    circumstances: ["free", "solo-friendly", "step-free", "beginner-welcome"],
    goingCount: 38, matchScore: 0.65,
    source: { name: "Meetup", url: "https://meetup.com/toronto-language-exchange" },
    imageUrl: null,
    description: "Twenty minutes per table, then everyone moves one seat over."
  },
  {
    id: "evt_034",
    title: "Improv jam, watch or play",
    venue: "Bad Dog Theatre, Bloor",
    startsAt: at("21:20"), endsAt: at("23:00"),
    travelMinutes: 27, travelMode: "transit",
    price: 10, currency: "CAD",
    tags: ["comedy", "social"],
    circumstances: ["solo-friendly", "beginner-welcome"],
    goingCount: 29, matchScore: 0.54,
    source: { name: "Venue site", url: "https://baddogtheatre.com" },
    imageUrl: null,
    description: "Names in a hat at nine, teams drawn at random."
  },
  {
    id: "evt_035",
    title: "Cycling club social ride, no drops",
    venue: "Sweet Pete's, Bloor and Bathurst",
    startsAt: at("18:00"), endsAt: at("20:00"),
    travelMinutes: 20, travelMode: "bike",
    price: 0, currency: "CAD",
    tags: ["outdoors", "fitness"],
    circumstances: ["free", "beginner-welcome", "solo-friendly"],
    goingCount: 23, matchScore: 0.48,
    source: { name: "Instagram", url: "https://instagram.com/sweetpetesbike" },
    imageUrl: null,
    description: "Thirty flat kilometres at a talking pace. Lights required, they will lend you one."
  },
  {
    id: "evt_036",
    title: "Pottery wheel taster, two hours",
    venue: "Clay Design Studio, Parkdale",
    startsAt: at("18:30"), endsAt: at("20:30"),
    travelMinutes: 46, travelMode: "transit",
    price: 65, currency: "CAD",
    tags: ["art", "making"],
    circumstances: ["beginner-welcome", "no-alcohol", "step-free"],
    goingCount: 8, matchScore: 0.29,
    source: { name: "Eventbrite", url: "https://eventbrite.ca/e/clay-design-taster" },
    imageUrl: null,
    description: "Two pieces fired and ready for pickup in three weeks."
  },
  {
    id: "evt_037",
    title: "Poetry open floor, sign up inside",
    venue: "Pauper's Pub, Bloor",
    startsAt: at("21:10"), endsAt: at("23:00"),
    travelMinutes: 25, travelMode: "transit",
    price: 0, currency: "CAD",
    tags: ["books", "music"],
    circumstances: ["free", "solo-friendly"],
    goingCount: 14, matchScore: 0.59,
    source: { name: "Facebook", url: "https://facebook.com/groups/paupersopenfloor" },
    imageUrl: null,
    description: "Three minutes each, upstairs room, nobody claps until the end."
  },
  {
    id: "evt_038",
    title: "Table tennis at the community centre",
    venue: "Scadding Court Community Centre",
    startsAt: at("17:00"), endsAt: at("19:00"),
    travelMinutes: 7, travelMode: "walk",
    price: 2, currency: "CAD",
    tags: ["games", "fitness"],
    circumstances: ["step-free", "kid-friendly", "no-alcohol", "solo-friendly"],
    goingCount: 11, matchScore: 0.45,
    source: { name: "Venue site", url: "https://scaddingcourt.org" },
    imageUrl: null,
    description: "Four tables in the gym. Two dollars at the desk, paddles provided."
  },
  {
    id: "evt_039",
    title: "Night market, food stalls until late",
    venue: "Stackt Market, Bathurst",
    startsAt: at("17:30"), endsAt: at("22:00"),
    travelMinutes: 13, travelMode: "walk",
    price: 0, currency: "CAD",
    tags: ["food", "social", "outdoors"],
    circumstances: ["free", "kid-friendly", "step-free", "solo-friendly"],
    goingCount: 72, matchScore: 0.67,
    source: { name: "Instagram", url: "https://instagram.com/stacktmarket" },
    imageUrl: null,
    description: "Twenty vendors in the container yard, live set on the small stage at eight."
  },
  {
    id: "evt_040",
    title: "Late run, harbourfront loop, 8k",
    venue: "HTO Park",
    startsAt: at("21:45"), endsAt: at("22:45"),
    travelMinutes: 18, travelMode: "walk",
    price: 0, currency: "CAD",
    tags: ["outdoors", "fitness"],
    circumstances: ["free", "solo-friendly"],
    goingCount: 10, matchScore: 0.42,
    source: { name: "Meetup", url: "https://meetup.com/toronto-late-runners" },
    imageUrl: null,
    description: "Steady six minute kilometres along the water, back at the same spot."
  }
];

export const SEED_USER = {
  origin: { lat: 43.6532, lng: -79.3832, label: "Queen & Spadina" },
  maxTravelMinutes: 45,
  freeWindows: [
    { startsAt: at("18:30"), endsAt: at("21:00") }
  ],
  interests: ["games", "outdoors", "music"],
  circumstances: ["solo-friendly", "free"]
};

export async function loadEvents() {
  if (!USE_API) return SEED_EVENTS;
  const r = await fetch(API_URL);
  if (!r.ok) throw new Error(`events ${r.status}`);
  return r.json();
}
